version: "3.9"

services:
  cnab_desafio:
    container_name: cnab_database
    image: postgres:14
    env_file: .env
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}",
        ]
      interval: 5s
      timeout: 2s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql

  migrations:
    build: .
    command: python manage.py migrate
    depends_on:
      cnab_desafio:
        condition: service_healthy

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    depends_on:
      cnab_desafio:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

volumes:
  pgdata:
